if(NOT DEFINED NATIVE_CACHE OR NOT DEFINED TOKENIZER_DIR OR NOT DEFINED DESTINATION
   OR NOT DEFINED RUST_TOOLCHAIN OR NOT DEFINED ORT_ROOT)
  message(FATAL_ERROR "Native cache, tokenizer, toolchains, and writable license destination are required.")
endif()
file(MAKE_DIRECTORY "${DESTINATION}")
file(COPY "${NATIVE_CACHE}/licenses/" DESTINATION "${DESTINATION}")
file(GLOB_RECURSE candidates LIST_DIRECTORIES false "${NATIVE_CACHE}/cargo/registry/src/*")
foreach(source IN LISTS candidates)
  get_filename_component(name "${source}" NAME)
  if(name MATCHES "^(LICENSE|LICENCE|COPYING|COPYRIGHT|NOTICE|UNLICENSE)([.-].*)?$")
    file(RELATIVE_PATH relative "${NATIVE_CACHE}/cargo/registry/src" "${source}")
    get_filename_component(directory "${relative}" DIRECTORY)
    # Release paths are restricted to [A-Za-z0-9_./-]; crate versions may carry build metadata ("+").
    string(REPLACE "+" "_" directory "${directory}")
    file(MAKE_DIRECTORY "${DESTINATION}/rust-crates/${directory}")
    file(COPY "${source}" DESTINATION "${DESTINATION}/rust-crates/${directory}")
  endif()
endforeach()
set(rust_docs "${RUST_TOOLCHAIN}/share/doc/rust")
if(NOT EXISTS "${rust_docs}/COPYRIGHT-library.html")
  message(FATAL_ERROR "Rust standard library copyright notices are missing.")
endif()
file(MAKE_DIRECTORY "${DESTINATION}/rust-stdlib")
file(COPY "${rust_docs}/COPYRIGHT-library.html" "${rust_docs}/licenses"
     DESTINATION "${DESTINATION}/rust-stdlib")
file(MAKE_DIRECTORY "${DESTINATION}/onnxruntime")
file(COPY "${ORT_ROOT}/LICENSE" "${ORT_ROOT}/ThirdPartyNotices.txt" DESTINATION "${DESTINATION}/onnxruntime")
file(COPY "${TOKENIZER_DIR}/Cargo.lock" DESTINATION "${DESTINATION}")
